---
- name: Install Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes
  become: yes

- name: Ensure Apache2 service is started and enabled
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: yes
  become: yes

- name: Create a simple Apache index page for app2
  ansible.builtin.copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>Welcome to App Server 2 (Apache)!</title>
      </head>
      <body>
        <h1>Success! App Server 2 with Apache is running.</h1>
        <p>DevOps rocks!</p>
      </body>
      </html>
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Restart Apache2