---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600 # Only update if cache is older than 1 hour
  become: yes 

- name: Install common packages
  ansible.builtin.apt:
    name:
      - curl
      - vim
      - git
      - unzip
      - python3-pip # Useful for many things, and Ansible itself might leverage it
    state: present
  become: yes