
---
- name: Configure Application Servers
  hosts: app_servers 
  become: yes
  roles:
    - common 
    - node_exporter

# Play 2: Configure Nginx on App Server 1
- name: Configure Nginx on App Server 1
  hosts: app1 
  become: yes
  roles:
    - nginx

# Play 3: Configure Apache on App Server 2
- name: Configure Apache on App Server 2
  hosts: app2 
  become: yes
  roles:
    - apache